In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../results/table_mechanistic.csv')

In [3]:
df

,paradigm,n_rows,failure_rate,generator_output_tokens_mean,generator_output_tokens_std,metric_n_samples_mean,metric_n_samples_std,selfcheck_sample_tokens_mean_mean,selfcheck_sample_tokens_mean_std,detection_overhead_ms_mean,...,n_retrieved_topk_mean,n_retrieved_topk_std,metric_index_size_mean,metric_index_size_std,metric_vector_store_mb_mean,metric_vector_store_mb_std,judge_prompt_tokens_mean,judge_prompt_tokens_std,metric_judge_output_tokens_mean,metric_judge_output_tokens_std
0,selfcheckgpt,100,0.00,235.75,85.770468,3.0,0.0,204.053333,52.530868,21298.918437,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,rag_verification,100,0.00,235.75,85.770468,NaN,NaN,NaN,NaN,18.494461,...,3.0,0.0,100.0,0.0,0.146484,0.0,NaN,NaN,NaN,NaN
2,llm_as_judge,100,0.03,235.75,85.770468,NaN,NaN,NaN,NaN,2071.558848,...,NaN,NaN,NaN,NaN,NaN,NaN,274.18,85.961864,59.92,13.683788

In [4]:
df1 = pd.read_csv('../../results_paper/table_mechanistic.csv')

In [5]:
df1

,paradigm,n_rows,failure_rate,generator_output_tokens_mean,generator_output_tokens_std,metric_n_samples_mean,metric_n_samples_std,selfcheck_sample_tokens_mean_mean,selfcheck_sample_tokens_mean_std,detection_overhead_ms_mean,...,n_retrieved_topk_mean,n_retrieved_topk_std,metric_index_size_mean,metric_index_size_std,metric_vector_store_mb_mean,metric_vector_store_mb_std,judge_prompt_tokens_mean,judge_prompt_tokens_std,metric_judge_output_tokens_mean,metric_judge_output_tokens_std
0,selfcheckgpt,200,0.00,204.41,99.684033,5.0,0.0,183.642,52.134386,36717.682430,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,rag_verification,200,0.00,204.41,99.684033,NaN,NaN,NaN,NaN,15.853918,...,3.0,0.0,100.0,0.0,0.146484,0.0,NaN,NaN,NaN,NaN
2,llm_as_judge,200,0.09,204.41,99.684033,NaN,NaN,NaN,NaN,2214.802716,...,NaN,NaN,NaN,NaN,NaN,NaN,242.77,99.85254,55.07,19.096294